# Generated by Django 3.1.4 on 2020-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=11)),
                ('starting_date', models.DateField(verbose_name='date published')),
                ('due_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
