# Generated by Django 3.1.4 on 2020-12-26 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20201226_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
